services:
    #nginx
    web:
        image: nginx:latest
        ports:
          - "80:80"
        volumes:
          - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
          - ./assets:/var/www/html/assets
    #php
    app: 
        build:
            context: .
            dockerfile: ./php/Dockerfile
        volumes:
            - ./app:/var/www/html
        environment:
            MYSQL_HOST: db
            MYSQL_PORT: 3306
            MYSQL_PASSWORD: secretuser
            MYSQL_DATABASE: docker-php
            MYSQL_USER: user
    #mysql
    db:
        image: mysql:latest
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: user
            MYSQL_PASSWORD: secretuser
            MYSQL_DATABASE: docker-php

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        ports:
            - 8001:80
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306

volumes:
    mysqldata:
