services:
    #nginx
    web:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        ports:
          - "8080:80"
        volumes:
          - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    #php
    app:
        build:
            context: .
            dockerfile: ./php/Dockerfile
    #mysql
    db:
        image: mysql:latest
        volumes:
            - mysqldata:/var/lib/mysqlpd
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: user
            MYSQL_PASSWORD: secretuser
            MYSQL_DATABASE: docker-php
    
volumes:
    mysqldata:
